version: '3'
services:
  app1:
    build:
      context: ./app1
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    networks:
      - mynetwork

  app2:
    build:
      context: ./app2
    ports:
      - "3001:3001"
    depends_on:
      - mariadb
    networks:
      - mynetwork

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: my_secure_root_password
      MYSQL_DATABASE: santiagodb
      MYSQL_USER: MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: Maria.2023admin
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
